mixin AppStrings {
  static const string = {"en": englishString};

  static const englishString = {
    "ok": "Ok",
    "cancel": "Cancel",
    "edit": "Edit",
    "exit": "Exit",
    "view": "View",
    "status": "Status",
    "verify": "Verify",
    "alert": "Alert",
    "login": "Login",
    "logout": "Logout",
    "yes": "Yes",
    "no": "No",
    "alert_logout": "Are you sure want to Logout?",
    "click_here": "Click here",
    "submit": "Submit",
    "delete": "Delete",
    "add_new": "Add New",
    "welcome": "Welcome To",
    "alert_delete": "Are sure want to delete?",
    "no_data_found": "No data found",
    "app_name": "Chime",
    "name": "Name",
    "name_e": "Enter name",
    "email_id": "Email id",
    "email_id_e": "Enter email id",
    "email_id_v": "Enter valid email id",
    "password": "Password",
    "password_e": "Enter password",
    "password_v": "Password must be at least 6 characters",
    "demo_credentials": "Demo Login Credentials",
    "demo_email": "Email: task@example.com",
    "demo_password": "Password: Qwerty@123!",
    "fill": "Fill",
    "loading_text": "Loading please wait...",
    "users": "Users",
    "create_your_first_meeting": "Create Your First Meeting",
  };
}
